name: kafka
base: core26
build-base: devel
version: '4.2.0'
summary: Apache Kafka in a snap.
description: |
  This is a snap that bundles Apache Kafka together with other tools of its ecosystem in order to be used in Charmed Operators, providing automated operations management from day 0 to day 2 on the Apache Kafka real-time stream processing, on top of a Virtual Machine cluster and K8s cluster. It is an open source, end-to-end, production ready data platform on top of cloud native technologies.
grade: devel
confinement: strict

platforms:
  amd64:

system-usernames:
  _daemon_: shared

hooks:
  install:
    plugs:
      - network
      - network-bind
      - mount-observe

environment:
  JAVA_HOME: $SNAP/usr/lib/jvm/java-21-openjdk-amd64

slots:
  kafka-logs:
    interface: content
    content: logs
    source:
      read:
        - $SNAP_COMMON/var/log/kafka
  connect-logs:
    interface: content
    content: logs
    source:
      read:
        - $SNAP_COMMON/var/log/connect

apps:
  daemon:
    command: opt/kafka/bin/start-wrapper.bash
    daemon: simple
    install-mode: disable
    environment:
      LOG_DIR: $SNAP_COMMON/var/log/kafka
    plugs:
      - network
      - network-bind
      - removable-media
      - mount-observe
  log-dirs:
    command: opt/kafka/bin/bin-wrapper.bash
    plugs:
      - network
      - network-bind
      - mount-observe
    environment:
      bin_script: kafka-log-dirs.sh
  storage:
    command: opt/kafka/bin/bin-wrapper.bash
    plugs:
      - network
      - network-bind
      - mount-observe
    environment:
      bin_script: kafka-storage.sh
  consumer-perf-test:
    command: opt/kafka/bin/bin-wrapper.bash
    plugs:
      - network
      - network-bind
      - mount-observe
    environment:
      bin_script: kafka-consumer-perf-test.sh
  producer-perf-test:
    command: opt/kafka/bin/bin-wrapper.bash
    plugs:
      - network
      - network-bind
      - mount-observe
    environment:
      bin_script: kafka-producer-perf-test.sh
  configs:
    command: opt/kafka/bin/bin-wrapper.bash
    plugs:
      - network
      - network-bind
      - mount-observe
    environment:
      bin_script: kafka-configs.sh
  topics:
    command: opt/kafka/bin/bin-wrapper.bash
    plugs:
      - network
      - network-bind
      - mount-observe
    environment:
      bin_script: kafka-topics.sh
  console-consumer:
    command: opt/kafka/bin/bin-wrapper.bash
    plugs:
      - network
      - network-bind
      - mount-observe
    environment:
      bin_script: kafka-console-consumer.sh
  console-producer:
    command: opt/kafka/bin/bin-wrapper.bash
    plugs:
      - network
      - network-bind
      - mount-observe
    environment:
      bin_script: kafka-console-producer.sh
  consumer-groups:
    command: opt/kafka/bin/bin-wrapper.bash
    plugs:
      - network
      - network-bind
      - mount-observe
    environment:
      bin_script: kafka-consumer-groups.sh
  get-offsets:
    command: opt/kafka/bin/bin-wrapper.bash
    plugs:
      - network
      - network-bind
      - mount-observe
    environment:
      bin_script: kafka-get-offsets.sh
  reassign-partitions:
    command: opt/kafka/bin/bin-wrapper.bash
    plugs:
      - network
      - network-bind
      - mount-observe
    environment:
      bin_script: kafka-reassign-partitions.sh
  replica-verification:
    command: opt/kafka/bin/bin-wrapper.bash
    plugs:
      - network
      - network-bind
      - mount-observe
    environment:
      bin_script: kafka-replica-verification.sh
  run-class:
    command: opt/kafka/bin/bin-wrapper.bash
    plugs:
      - network
      - network-bind
      - mount-observe
    environment:
      bin_script: kafka-run-class.sh
  kafka-streams-application-reset:
    command: opt/kafka/bin/bin-wrapper.bash
    plugs:
      - network
      - network-bind
      - mount-observe
    environment:
      bin_script: kafka-streams-application-reset.sh
  transactions:
    command: opt/kafka/bin/bin-wrapper.bash
    plugs:
      - network
      - network-bind
      - mount-observe
    environment:
      bin_script: kafka-transactions.sh
  leader-election:
    command: opt/kafka/bin/bin-wrapper.bash
    plugs:
      - network
      - network-bind
      - mount-observe
    environment:
      bin_script: kafka-leader-election.sh
  dump-log:
    command: opt/kafka/bin/bin-wrapper.bash
    plugs:
      - network
      - network-bind
      - mount-observe
    environment:
      bin_script: kafka-dump-log.sh
  acls:
    command: opt/kafka/bin/bin-wrapper.bash
    plugs:
      - network
      - network-bind
      - mount-observe
    environment:
      bin_script: kafka-acls.sh
  cluster:
    command: opt/kafka/bin/bin-wrapper.bash
    plugs:
      - network
      - network-bind
      - mount-observe
    environment:
      bin_script: kafka-cluster.sh
  verifiable-consumer:
    command: opt/kafka/bin/bin-wrapper.bash
    plugs:
      - network
      - network-bind
      - mount-observe
    environment:
      bin_script: kafka-verifiable-consumer.sh
  verifiable-producer:
    command: opt/kafka/bin/bin-wrapper.bash
    plugs:
      - network
      - network-bind
      - mount-observe
    environment:
      bin_script: kafka-verifiable-producer.sh
  trogdor:
    command: opt/kafka/bin/bin-wrapper.bash
    plugs:
      - network
      - network-bind
      - mount-observe
    environment:
      bin_script: trogdor.sh
  metadata-quorum:
    command: opt/kafka/bin/bin-wrapper.bash
    plugs:
      - network
      - network-bind
      - mount-observe
    environment:
      bin_script: kafka-metadata-quorum.sh
  connect-distributed:
    command: opt/connect/bin/connect-wrapper.bash
    plugs:
      - network
      - network-bind
      - mount-observe
    daemon: simple
    install-mode: disable
    environment:
      LOG_DIR: $SNAP_COMMON/var/log/connect
  connect-plugin-path:
    command: opt/kafka/bin/bin-wrapper.bash
    plugs:
      - network
      - network-bind
      - mount-observe
    environment:
      bin_script: connect-plugin-path.sh
  keytool:
    command: usr/lib/jvm/java-21-openjdk-amd64/bin/keytool
    plugs:
      - mount-observe

parts:
  kafka:
    plugin: nil
    source: https://github.com/canonical/central-uploader/releases/download/kafka_2.13-$SNAPCRAFT_PROJECT_VERSION-ubuntu2/kafka_2.13-$SNAPCRAFT_PROJECT_VERSION-ubuntu2-20260423135317.tgz
    source-checksum: sha512/15407092a82c23695bea5f744051e0c61cad46a8b31791815c51e564dcac08fde6b665094c4bb2806d97a1306127d4bba5954a780e395dd5363bc3e27adf7e2d
    build-packages:
    - ca-certificates-java
    stage-packages:
    - openjdk-21-jre-headless
    - util-linux
    - libpsl5
    - curl
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/opt/kafka
      cp -r ./* $CRAFT_PART_INSTALL/opt/kafka
    override-prime: |
      craftctl default
      mkdir -p $CRAFT_PRIME/opt/kafka/libs

  wrapper:
    plugin: dump
    source: snap/local
