name: Build and Test

on:
  workflow_dispatch:
  pull_request:

jobs:
  lint:
    name: Lint Prometheus Exporter
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install tox & uv
        run: |
          sudo snap install --classic astral-uv
          pipx install tox
      - name: Run linters
        working-directory: ./prometheus
        run: tox run -e lint

  build:
    name: Build snap
    uses: canonical/data-platform-workflows/.github/workflows/build_snap.yaml@v32.0.0

  test:
    name: Test Snap
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download snap package
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ needs.build.outputs.artifact-prefix }}-*
          merge-multiple: true

      - name: Install snap file
        run: |
          sudo snap install charmed-kafka*.snap --dangerous

      - name: Set default configs
        run: |
          # Copy default configs from Apache Kafka sources
          sudo cp /snap/charmed-kafka/current/opt/kafka/config/server.properties /var/snap/charmed-kafka/current/etc/kafka/server.properties
          sudo cp /snap/charmed-kafka/current/opt/kafka/config/connect-distributed.properties /var/snap/charmed-kafka/current/etc/connect
          sudo cp /snap/charmed-kafka/current/opt/cruise-control/config/cruisecontrol.properties /var/snap/charmed-kafka/current/etc/cruise-control

          # Configure log.dirs
          sudo sed -i '/log.dirs=/c\log.dirs=/var/snap/charmed-kafka/common/var/log/kafka' /var/snap/charmed-kafka/current/etc/kafka/server.properties

          # Configure cruise control
          sudo sed -i -e 's/sample.store.topic.replication.factor=2/sample.store.topic.replication.factor=1/g' /var/snap/charmed-kafka/current/etc/cruise-control/cruisecontrol.properties
          sudo sed -i -e 's|capacity.config.file=config/capacityJBOD.json|capacity.config.file=/var/snap/charmed-kafka/current/etc/cruise-control/capacityJBOD.json|g' /var/snap/charmed-kafka/current/etc/cruise-control/cruisecontrol.properties
          sudo sed -i -e '/zookeeper.connect=localhost:2181\//c\# zookeeper.connect=localhost:2181/' /var/snap/charmed-kafka/current/etc/cruise-control/cruisecontrol.properties
          sudo sed -i -e '/zookeeper.security.enabled=false/c\# zookeeper.security.enabled=false' /var/snap/charmed-kafka/current/etc/cruise-control/cruisecontrol.properties
          sudo sed -i -e '/# zookeeper.security.enabled=false/a\kafka.broker.failure.detection.enable=true\n' /var/snap/charmed-kafka/current/etc/cruise-control/cruisecontrol.properties

          sudo cp /snap/charmed-kafka/current/opt/cruise-control/config/capacityJBOD.json /var/snap/charmed-kafka/current/etc/cruise-control

          # Format storage
          uuid=$(sudo charmed-kafka.storage random-uuid)
          sudo charmed-kafka.storage format --standalone --cluster-id $uuid -c /var/snap/charmed-kafka/current/etc/kafka/server.properties

          sudo chown -R _daemon_:_daemon_ /var/snap/charmed-kafka/common/var/log/kafka

      - name: Start snap services
        run: |
          sudo snap start charmed-kafka.daemon
          sleep 10

      - name: Check topic creation
        run: |
          topic_creation=$(sudo charmed-kafka.topics --create --topic __CruiseControlMetrics --bootstrap-server localhost:9092)
          echo $topic_creation
          if [[ "$topic_creation" == *"Created topic __CruiseControlMetrics."* ]]; then
              exit 0
          fi
          exit 1

      - name: Test Connect service
        run: |
          sudo snap start charmed-kafka.connect-distributed
          sleep 20
          result=$(curl -s http://localhost:8083)
          echo $result
          if [[ "$result" == *"kafka_cluster_id"* ]]; then
              exit 0
          fi
          exit 1

      - name: Check CruiseControl state
        run: |
          sudo snap start charmed-kafka.cruise-control
          sleep 20
          curl -s http://localhost:9090/kafkacruisecontrol/state | grep "state: RUNNING"

      - uses: actions/checkout@v6
      - name: Test python exporter
        uses: ./.github/actions/test_python_exporter

      - name: Check logging
        run: |
          sudo cp ./tests/config/server.properties /var/snap/charmed-kafka/current/etc/kafka/server.properties
          sudo cp ./tests/config/client.properties /var/snap/charmed-kafka/current/etc/kafka/
          sudo cp ./tests/config/admin-client.properties /var/snap/charmed-kafka/current/etc/kafka/

          # Change logging level to DEBUG
          echo "KAFKA_CFG_LOGLEVEL=DEBUG" | sudo tee -a /etc/environment

          # reset services
          sudo snap restart charmed-kafka.daemon

          # For state change loggers, create a test topic and produce some messages
          sudo charmed-kafka.topics \
            --bootstrap-server localhost:9092 \
            --command-config /var/snap/charmed-kafka/current/etc/kafka/admin-client.properties \
            --create --topic test

          i=1
          while [ $i -le 5 ]
          do
            echo "MESSAGE $i" | \
              sudo charmed-kafka.console-producer \
              --bootstrap-server localhost:9092 \
              --producer.config /var/snap/charmed-kafka/current/etc/kafka/admin-client.properties \
              --topic test
            i=$((i+1))
          done

          # For authorizer logger, try to consume with non-authorized user
          sudo charmed-kafka.console-consumer \
            --bootstrap-server localhost:9092 \
            --consumer.config /var/snap/charmed-kafka/current/etc/kafka/client.properties \
            --topic test \
            --from-beginning \
            --max-messages 3

          echo "Asserting Broker Logs:"
          sudo ls -lh /var/snap/charmed-kafka/common/var/log/kafka/ | grep .log
          for filename in server.log kafka-authorizer.log kafka-request.log state-change.log; do
            if sudo test -s "/var/snap/charmed-kafka/common/var/log/kafka/$filename"; then
              echo "$filename exists and is not empty" 
            else
              echo "$filename is empty!"
              exit 1
            fi
          done

          echo "Asserting Connect Logs:"
          sudo ls -lh /var/snap/charmed-kafka/common/var/log/connect/ | grep .log
          for filename in connect.log; do
            if sudo test -s "/var/snap/charmed-kafka/common/var/log/connect/$filename"; then
              echo "$filename exists and is not empty" 
            else
              echo "$filename is empty!"
              exit 1
            fi
          done

          echo "Asserting CruiseControl Logs:"
          sudo ls -lh /var/snap/charmed-kafka/common/var/log/cruise-control/ | grep .log
          for filename in kafkacruisecontrol-operation.log kafkacruisecontrol-request.log kafkacruisecontrol.log; do
            if sudo test -s "/var/snap/charmed-kafka/common/var/log/cruise-control/$filename"; then
              echo "$filename exists and is not empty" 
            else
              echo "$filename is empty!"
              exit 1
            fi
          done
