#!/usr/bin/env bash
# Installation hook for charmed-kafka snap.
#
# Note: '584788' refers to the snap_daemon user and group within a snap,
# exposed as user ID (UID) and group ID (GID).
#
# FIXME (24.04): From snapd 2.61 onwards, snap_daemon is being deprecated and
# replaced with _daemon_ (with underscores), which now possesses a UID of 584792.
# See https://snapcraft.io/docs/system-usernames.

set -eux

for COMPONENT in kafka kafka-connect cruise-control
do
    export CONF="${SNAP_DATA}"/etc/$COMPONENT
    export LOGS="${SNAP_COMMON}"/var/log/$COMPONENT
    export DATA="${SNAP_COMMON}"/var/lib/$COMPONENT

    mkdir -p $CONF
    mkdir -p $LOGS
    mkdir -p $DATA

    # setting dir permissions given re-attached storage
    if [stat -c '%u' "$DATA" == 0 -o ! -d "$DATA"]; then
        chmod -R 770 "${SNAP_COMMON}"
        chown -R 584788:root "${SNAP_COMMON}"
        chmod 750 "${DATA}"
        chown 584788:root "${DATA}"
    else
        chmod -R 770 "${LOGS}"
        chown -R 584788:root "${LOGS}"
    fi

    # copying default config from squashfs
    cp -R "${SNAP}"/etc/$COMPONENT/* $CONF
done

# setting blanket permissions for the installing snap data dir
chmod -R 770 "${SNAP_DATA}"/*
chown -R 584788:root "${SNAP_DATA}"/*
