#!/usr/bin/env bash
# Installation hook for charmed-kafka snap.
#
# Note: '584792' refers to the _daemon_ user and group within a snap,
# exposed as user ID (UID) and group ID (GID).

set -eux

for COMPONENT in kafka cruise-control connect
do
    export CONF="${SNAP_DATA}"/etc/$COMPONENT
    export LOGS="${SNAP_COMMON}"/var/log/$COMPONENT
    export DATA="${SNAP_COMMON}"/var/lib/$COMPONENT

    mkdir -p $CONF
    mkdir -p $LOGS
    mkdir -p $DATA

    # setting dir permissions given re-attached storage
    if [stat -c '%u' "$DATA" == 0 -o ! -d "$DATA"]; then
        chmod -R 770 "${SNAP_COMMON}"
        chown -R 584792:root "${SNAP_COMMON}"
        chmod 750 "${DATA}"
        chown 584792:root "${DATA}"
    else
        chmod -R 770 "${LOGS}"
        chown -R 584792:root "${LOGS}"
    fi

    # copying default config from squashfs
    cp "${SNAP}"/etc/$COMPONENT/* $CONF
done

# setting blanket permissions for the installing snap data dir
chmod -R 770 "${SNAP_DATA}"/*
chown -R 584792:root "${SNAP_DATA}"/*
